# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('satellite-constellation', ['core', 'mobility', 'network', 'csma', 'point-to-point', 'internet', 'applications', 'flow-monitor', 'satellite'])
    module.source = [
        'model/satellite-network-config.cc',
        'model/mobility/full-ground-station-mobility.cc',
        'model/orbital/orbital-coords.cc',
        'model/orbital/sgp4math.cc',
        
        ]
# 'model/mobility/leo-satellite-mobility.cc',
# 'helper/leo-satellite-helper.cc',

    module_test = bld.create_ns3_module_test_library('satellite-constellation')
    module_test.source = [
        'test/satellite-constellation-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'satellite-constellation'
    headers.source = [
        'model/leo-satellite-config.h',    
        'model/mobility/full-ground-station-mobility.h',
        'model/orbital/orbital-coords.h',
        'model/orbital/sgp4math.h'
        ]
    # 'model/mobility/leo-satellite-mobility.h',

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

